### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by sangyoo91** [ajduke/meteor-bootstrap-tagsinput#10]
I've inserted tags as arrays flawlessly using 
True multi value (select multiple).

I am retrieving these values using
```
tags: function() {
		return Posts.findOne({_id:this._id}).tags;
	}
```

```
{{#each tags}}
 <span class="tags">{{this}}</span>
{{/each}}
```

its working perfectly.

The problem is, when I try to insert these tags back when I go to my edit section.

How do I retrieve arrays from mongo with this.

This is my collection structure.
```
posts{
    tags {
        0 : "tag 1"
        1 : "tag 2"
       and so forth.
    }
}
````

**Comment by ajduke** [comment]
I see you are using `span` for displaying tags,.
How you are getting new entered tags from user? 
do you use `input`  ?

**Comment by ajduke** [comment]
I am unable understand the question, can you please explain it again?
