### ISSUE TITLE
Using typeahead

### ISSUE THREAD

**Issue by sangyoo91** [ajduke/meteor-bootstrap-tagsinput#11]
```
$('.tagsinput').tagsinput({
		confirmKeys: [13, 32, 188], //Enter Space Comma
		maxTags: 5,
		trimValue: true,
		maxChars: 16,
		tagClass: 'label label-default tagCustom',
		typeahead: {
    		source: ['css', 'javascript', 'jquery', 'meteor', 'mongodb', 'php', 'mysql', 'clojure', 'html', 'less']
 		},
 		freeinput: true
	});
```
This is not working for me.
I don't see a dropdown for typeahead. What is the problem? 

How would I use typeahead?

**Comment by ajduke** [comment]
I did not tested typeahead after porting repo, but let me check if anything missing 
But Did you try adding the typeahead.js ?

**Comment by sangyoo91** [comment]
@ajduke I have tried this with https://atmospherejs.com/sergeyt/typeahead. I've had no luck :(

**Comment by ajduke** [comment]
I will check it out tonight and will let you know.

Thanks
/ajduke

**Comment by sangyoo91** [comment]
@ajduke Thanks: ) Please let me know

**Comment by sangyoo91** [comment]
Is there any progress on this?

**Comment by ajduke** [comment]
I installed typeahead package from Atomsphere and put the following rendered function of template-

I guess you need to use the Bloodhound Suggestion engine with adapter as shown in following code.

```
Template.hello.rendered = function(){

    var citynames = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: [{name:"one"}, {name:"two"}, {name:"three"}]
    });
    citynames.initialize();

    $('.typeahead').tagsinput({
      typeaheadjs: {
        name: 'citynames',
        displayKey: 'name',
        valueKey: 'name',
        source: citynames.ttAdapter()
      }
    });
  }
```


and html as follows -


`<input class="typeahead" name="team" type="text">`

Hope this helps. 

I am closing for this now.
