### ISSUE TITLE
Script does not load when used in template

### ISSUE THREAD

**Issue by methodbox** [ajduke/meteor-bootstrap-tagsinput#13]
I am unable to make this script load without manually calling the script from within the template for my form where I'm attempting to use these tags.

Installing the Meteor package does nothing.

I am using this to force-call the script:

```
<script type="text/javascript">
  $.getScript('http://timschlechter.github.io/bootstrap-tagsinput/dist/bootstrap-tagsinput.js',
  function(){});
</script>
```

**Comment by ajduke** [comment]
Hello @methodbox ,

Please provide which version of Meteor you are using?
and i am considering you are using `meteor add` command to install the package

**Comment by dmayo2** [comment]
Same issue here. JS file is loading. Yes, installed by cli: `meteor add ajduke:bootstrap-tagsinput` which resulted in: `ajduke:bootstrap-tagsinput  added, version 0.7.0`. Using `Meteor 1.1.0.2`

**Comment by danielapsmaior** [comment]
Same here with 
METEOR@1.2.0.2
ajduke:bootstrap-tagsinput@0.7.0

**Comment by ajduke** [comment]
Updated newer version of package, it should resolve this
