### ISSUE TITLE
Styles added to input tags by script using "!important" - cannot be overridden

### ISSUE THREAD

**Issue by methodbox** [ajduke/meteor-bootstrap-tagsinput#14]
Within your script you are using a ```style=``` attribute on a script-rendered input tag.

This script works by removing the user-created input tag element and replacing it with the one generated with your script.  You should not be forcing styles when doing this.  Styles should ONLY be inherited from the original ```input``` element.

The problem is right here:
```
this.$input.get(0).style.cssText="width: "+d+" !important;",this.build(c)}
```

When this ```!important``` value is assigned and bootstrap-tagsinput is used with Meteor, the style cannot be overridden, resulting in unpredictable element widths set in ```em``` values. This is due to the nature with which Meteor renders page elements with templates. Not only does it make no sense to enforce a specific element with, it makes absolutely no sense to do it using ```em``` values.  The field inherits the ```em``` value from the parent element and seems to pick a random size between 27 and 29em.

Please either remove the ```!important``` or remove the style property altogether.

**Comment by ajduke** [comment]
This is just Meteor Port of [bootstrap-tagsinput](https://github.com/timschlechter/bootstrap-tagsinput),

I added that project as git sub module and cant change anything from there, if you have any questions pertaining to library, please create issue at  [bootstrap tagsinput issues](https://github.com/timschlechter/bootstrap-tagsinput/issues),
