### ISSUE TITLE
Manually start tagsinput

### ISSUE THREAD

**Issue by TechplexEngineer** [ajduke/meteor-bootstrap-tagsinput#16]
Should one have to manually start tagsinput on input fields with the `data-role="tagsinput"` attribute.

I had to insert the following code to start tagsinput
```
Template.myTemplate.onRendered(function () {
    $('[data-role="tagsinput"]').tagsinput();
});
```

**Comment by ajduke** [comment]
Updated new version of package, it should resolve this issue.
