### ISSUE TITLE
bug ?

### ISSUE THREAD

**Issue by pociej** [ajduke/meteor-bootstrap-tagsinput#5]
=> Errors while scanning packages:

While building package `bootstrap-tagsinput`:
error: File not found: lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js
error: File not found: lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.css

/usr/local/lib/node_modules/meteorite/lib/command.js:41
            throw "Command exited with " + code + "/" + signal;
                                                      ^
Command exited with 1/null

**Comment by ajduke** [comment]
Reopen if it does not solved issue
