### ISSUE TITLE
Why Bootstrap-3 hard dependency?

### ISSUE THREAD

**Issue by Helmi** [ajduke/meteor-bootstrap-tagsinput#9]
Is there any reason to use a hard dependency to the mizzao:bootstrap-3 package instead of a weak one? A weak dependency would allow people to easily use their beloved package without having to force install an older version.

Thanks

**Comment by ajduke** [comment]
The basic reason is that package is used mostly by developers (as from no. of downloads from atmosphere.com ).

and What do you mean by weak dependency, here, please explain?

Regards,
/ajduke

**Comment by Helmi** [comment]
A weak dependency doesn't autoinstall a package. There's no need to add hard dependency on a bootstrap package usually as any bootstrap package mostly does the trick. For explanation on weak dependencies look at the Meteor API docs http://docs.meteor.com/#/full/pack_use

**Comment by ajduke** [comment]
Coool, let me look into it properly and Thanks , btw.

Regards,
/ajduke

**Comment by steinitz** [comment]
Hi,

Thanks for your good work on ajduke:bootstrap-tagsinput.

A weak dependency would be a big help.  As an example, cloudspider:auto form-tags-tepeahead depends on your package version 0.7.1.  When using memo64:bootstrap, the forced load of twbs:bootstrap causes issues which are hard to diagnose, for example, ian:accounts-ui doesn't work at all.

I hope these comments are useful.

**Comment by CarlQLange** [comment]
yes, I really wish this was the case. I can't use this package without it, for the same reasons that @steinitz explained.

**Comment by s1rd4v3** [comment]
same here. i'm using a custom bs3 so i don't have to include the whole monster and just picking what i need. your twbs:bootstrap dependency does brake my app afterwards. would be great if we could decide by our own which bootstrap to include. i think every dev should be capable of adding one on his own ;)

__Thanks for your work!__
